"""Render the shop domain's Mermaid diagram to ``diagram.md``.

    python -m examples.shop.diagram --write   # regenerate the committed diagram
    python -m examples.shop.diagram --check   # fail if the committed diagram is stale

CI runs ``--check`` so the committed diagram never drifts from the domain definition.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from dddantic import diagram
from examples.shop import domain

_DOC_PATH = Path(__file__).with_name("diagram.md")
_HEADER = (
    "# Shop domain diagram\n\n"
    "Generated by `python -m examples.shop.diagram --write`. Do not edit by hand.\n\n"
)


def _block(title: str, mermaid: str) -> str:
    return f"## {title}\n\n```mermaid\n{mermaid}\n```\n\n"


def render_markdown() -> str:
    """Build the Markdown document: context map, grouped overview, per-context diagrams."""
    parts = [
        _HEADER,
        _block("Context map", diagram.to_context_map()),
        _block("Overview (all contexts)", diagram.to_mermaid(group_by_context=True)),
    ]
    parts.extend(_block(ctx, diagram.to_mermaid(within=ctx)) for ctx in domain.CONTEXTS)
    return "".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Render the shop domain diagram.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail if diagram.md is stale")
    mode.add_argument("--write", action="store_true", help="regenerate diagram.md")
    args = parser.parse_args()

    content = render_markdown()
    if args.check:
        current = _DOC_PATH.read_text(encoding="utf-8") if _DOC_PATH.exists() else ""
        if current != content:
            print("diagram.md is out of date. Run: python -m examples.shop.diagram --write")
            return 1
        print("diagram.md is up to date.")
        return 0
    _DOC_PATH.write_text(content, encoding="utf-8")
    print(f"wrote {_DOC_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
